name: $(Date:yyyyMMdd)$(Rev:.r)

trigger:
  - master
  - sandbox
  - vNext

stages:
- stage: Build
  jobs:
  - job: BuildJob
    displayName: Build & Publish to Docker
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: PowerShell@2
      inputs:
        targetType: 'inline'
        script: |
          switch(${env:BUILD_SOURCEBRANCH}) {
            'refs/heads/master' {
              Write-Host "##vso[task.setvariable variable=nodeVersion]10.x"
              Write-Host "##vso[task.setvariable variable=buildCommand]build-prod"
              }
            'refs/heads/sandbox' {
              Write-Host "##vso[task.setvariable variable=nodeVersion]10.x"
              Write-Host "##vso[task.setvariable variable=buildCommand]build-prod"
              }
            'refs/heads/vNext' {
              Write-Host "##vso[task.setvariable variable=nodeVersion]12.x"
              Write-Host "##vso[task.setvariable variable=buildCommand]buildProduction"
              }
          }
      displayName: 'Set build variables'

    - task: UseNode@1
      inputs:
        version: $(nodeVersion)
      displayName: 'Install Node'

    - task: Npm@1
      inputs:
        command: 'install'
      displayName: 'Install NPM'

    - task: gulp@1
      inputs:
        targets: '$(buildCommand)'
        enableCodeCoverage: false
      displayName: 'Build release using gulp'

    - task: CopyFiles@2
      inputs:
        Contents: '$(Build.SourcesDirectory)/dist/**'
        targetFolder: $(Build.ArtifactStagingDirectory)
      displayName: 'Copy dist to Artifact Staging'

    - task: PublishBuildArtifacts@1
      inputs:
        pathtoPublish: '$(Build.ArtifactStagingDirectory)/dist/'
        artifactName: MEA-artifact
      displayName: 'Publish Staged Artifacts to "MEA-artifact"'

    - task: Docker@2
      inputs:
        containerRegistry: 'sidewinder53@hub.docker.com'
        repository: 'sidewinder53/mea'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: 'vnext-$(Build.BuildId)'

- stage: Deploy
  jobs:
  - deployment: DeployApp
    displayName: Deploy to Environment
    environment:
      name: 'vNext-Staging'
      resourceType: 'virtualMachine'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: DownloadBuildArtifacts@0
            inputs:
              buildType: 'specific'
              project: '70dbfa67-3af7-4823-97b8-a474e59f0749'
              pipeline: '8'
              buildVersionToDownload: 'latest'
              downloadType: 'single'
              artifactName: 'cfgpkg'
              downloadPath: '$(System.ArtifactsDirectory)'

          - script: |
              cd /var/container/mea/vNext
              cp -f $(System.ArtifactsDirectory)/cfgpkg/cherry/vNext/docker-compose.yml .
              sed -i 's|sidewinder53/mea:vnext-|sidewinder53/mea:vnext-$(Build.BuildId)|g' docker-compose.yml
              docker-compose up -d --force-recreate
            displayName: Deploy Container
