trigger:
  - vNext

pool:
  vmImage: "ubuntu-latest"

steps:
  - task: UseNode@1
    inputs:
      version: "12.x"

  - script: |
      npm install
    displayName: "Install NPM"

  - script: |
      npm run buildProduction
    displayName: "Build for Development"

  - task: CopyFiles@2
    inputs:
      Contents: $(Build.SourcesDirectory)/dist/**
      targetFolder: $(Build.ArtifactStagingDirectory)
    displayName: "Copy distributable resources to Artifact Staging Directory"

  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: "$(Build.ArtifactStagingDirectory)"
      artifactName: MEA-vNext-artifact
    displayName: 'Publish Staged Artifacts to "MEA-vNext-artifact"'
